version: "3"
services:
  consumer:
    build: ./ConsumerMq
    image: somkiat/consumer
    environment:
      - RABBIT_HOSTNAME=rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672