---
kind: Service
apiVersion: v1
metadata:
  name: my-consumer
spec:
  type: LoadBalancer
  selector:
    app: my-consumer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-consumer
  template:
    metadata:
      labels:
        app: my-consumer
    spec:
      containers:
      - name: consumer
        image: somkiat/consumer